### ISSUE TITLE
Comment on payload

### ISSUE THREAD

**Issue by edmondyu** [indiejoseph/zlib2iscn#1]
- The field contentFingerprint should be assigned with the book's IPFS(or AR) hash rather than the zlib URL.

- The zlib URL can be assigned to the "url" field of the ISCN.

- it will be helpful if the same value is assigned to the ISCN "sameAs" field, with a query string appended.  Please refer to the attached JSON for reference.

[iscn.json](https://github.com/indiejoseph/zlib2iscn/files/13467569/iscn.json)

**Comment by indiejoseph** [comment]
- contentFingerprint must be a list of uri, so i will remove zlib URL and keep IPFS url(ipfs://xxx)
- ok
- since this tool only directly copy the IPFS url from zlib, so only ipfs url available for sameAs, i will add this field
